# -*- coding: utf-8 -*-
{
    'name': 'Bluespace Report Extended',
    # 'version': '16.0',
    'version': '1.0',
    'category': 'Report Extended',
    'sequence': 1,
    'author': 'Erpweb',
    'images': [],
    'depends': ['base', 'auto_rental', 'sale_renting'],
    # 'sale_temporal', 
    'data': [
        'security/ir.model.access.csv',
        'data/action.xml',
        'report/sale_order_line_view.xml',
        'report/sale_renting_view.xml',
        'report/financial_occupation_view.xml',
        'report/warehouse_occupation_view.xml',
        'report/office_occupation_view.xml',
        'report/parking_occupation_view.xml',
        'report/boardroom_occupation_view.xml',
    ],
    'demo': [],
    'test': [],
    'application': True,
    'qweb': [],
    'auto_install': False,
    'license': 'OPL-1',
}

